import './index.scss'
import './blocks/header/header.js'
import './blocks/main/gallery/images-list/images-list.js'
import './blocks/main/key-properties/key-properties.js'
import './blocks/main/slider/slider.js'
import './blocks/footer/footer.js'
import './favicon/favicon.js'
import './php/php.js'